### ISSUE TITLE
Domain not showing as protected in APS

### ISSUE THREAD

**Issue by AndreiCristianIT** [SpamExperts/aps2-addon#28]
### Version information
ASP 2.0-17

### Steps to replicate

 1.Add a domain
 2.Try to protect the domain
 3.Domain doesn't show protected, but is added to the Control Panel

### Actual result
Domain doesn't show protected

### Expected result
Domain should show protected

### Other notes
WHMCS: #363669

**Comment by for93t** [comment]
I had a look into the debug log and found that the corresponding domain user is missing, that's why the protection does not look to be "complete" for the application. @AndreiCristianIT, please advice the client to create the corresponding domain user for the problematic domain manually and re-check the protection status. It should fix things for them.

**Comment by VicSpam01** [comment]
The problem persists even after the domain user was created. Probably some other cause.

**Comment by alexkiro** [comment]
> The problem persists even after the domain user was created. Probably some other cause.

The logs show that the domain now either belongs to a different admin, or no admin at all:

```
{"error":["You are not allowed to manage the domain \'example.com\'"]}
```

So that need to be fixed in the ControlPanel.
